# Generated by Django 5.2.1 on 2025-06-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=100)),
                ('produit', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
