# Generated by Django 5.2.1 on 2025-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
