# Generated by Django 5.2.1 on 2025-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='quantite_restante',
            field=models.IntegerField(default=0),
        ),
    ]
