# Generated by Django 5.2.1 on 2025-06-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=100)),
                ('produit', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('date_commande', models.DateTimeField()),
            ],
        ),
    ]
