# Generated by Django 5.2.1 on 2025-06-04 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=20)),
                ('produit', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'commandes',
            },
        ),
    ]
