# Generated by Django 5.2.1 on 2025-06-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'managed': False},
        ),
    ]
