# Generated by Django 5.2.1 on 2025-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
