# Generated by Django 5.2.1 on 2025-06-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0002_alter_commande_numero_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(max_length=100),
        ),
    ]
