# Generated by Django 5.2.1 on 2025-06-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0002_alter_commande_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
    ]
