# Generated by Django 5.2.1 on 2025-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0003_alter_commande_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_unitaire',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='commande',
            table=None,
        ),
    ]
