# Generated by Django 5.2.1 on 2025-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurconfiguration',
            name='nom',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
