# Generated by Django 5.2.1 on 2025-06-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('dateInscription', models.DateField()),
                ('produitsAchetes', models.TextField(blank=True, null=True)),
                ('montantTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nomVendeur', models.CharField(max_length=100)),
                ('modePaiement', models.CharField(max_length=50)),
            ],
        ),
    ]
